[tools]
aws = { version = "latest", symlink_bins = "true" }
bun = "latest"
claude = "latest"
deno = "latest"
direnv = "latest"
fzf = "latest"
go = "1.26"
golangci-lint = "latest"
granted = "latest"
herdr = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
node = "26"
nub = "latest"
opencode = "latest"
pnpm = "11"
terraform = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
