[tools]
aws = { version = "2.36", symlink_bins = "true" }
bun = "1.4"
claude = "2.1"
deno = "2.9"
fzf = "0.74"
go = "1.26"
golangci-lint = "2.13"
herdr = "0.9.0"
k9s = "0.51"
kubectl = "1.37"
lazydocker = "latest"
lazygit = "0.65"
neovim = "0.12"
node = "26"
nub = "0.9"
opencode = "1"
pnpm = "11"
terraform = "1.16"
uv = "0.12"
bottom = "0.14"
fastfetch = "2.68"
usage = "6.8"
jq = "latest"
gh = "2"
tree-sitter = "0.27"
ninja = "latest"
"postgres-binary:postgres" = "18"
starship = "latest"
ripgrep = "latest"
"vfox:jdx/vfox-mysql" = "8.4"
"github:bjarneo/cliamp" = "2"
zoxide = "latest"

[tools."github:dmtrKovalenko/fff"]
version = "0.10"
matching = "fff-mcp"
bin = "fff-mcp"

[settings]
idiomatic_version_file_enable_tools = ["node", "go", "npm", "pnpm"]

[settings.github]
credential_command = "gh auth token"

[plugins]
postgres-binary = "https://github.com/kyleking/mise-postgres-binary"

[bootstrap.repos]
"~/.antidote" = { url = "https://github.com/mattmc3/antidote.git", ref = "v2.2.1" }
"~/.config/nvim" = { url = "https://github.com/slagiewka/nvimconf.git", ref = "main" }
"~/code/work/dotfiles-work" = { url = "https://github.com/slagiewka/dotfiles-work.git", ref = "master" }

[dotfiles]
"~/.config/mise/miserc.toml" = "~/code/slagiewka/dotfiles/mise/miserc.toml"
"~/.config/mise/config.toml" = "~/code/slagiewka/dotfiles/mise/config.toml"
"~/.config/mise/config.macos.toml" = "~/code/slagiewka/dotfiles/mise/config.macos.toml"
"~/.config/mise/config.linux.toml" = "~/code/slagiewka/dotfiles/mise/config.linux.toml"
"~/.config/mise/conf.d/work.toml" = "~/code/work/dotfiles-work/work.toml"
"~/.config/fish/config.fish" = "~/code/slagiewka/dotfiles/fish/config.fish"
"~/.zshrc" = "~/code/slagiewka/dotfiles/zsh/.zshrc"
"~/.zsh_plugins.txt" = "~/code/slagiewka/dotfiles/zsh/.zsh_plugins.txt"
"~/.gitconfig" = "~/code/slagiewka/dotfiles/git/.gitconfig"
"~/.config/git/ignore" = "~/code/slagiewka/dotfiles/git/ignore"
"~/.config/ghostty" = "~/code/slagiewka/dotfiles/ghostty"

[bootstrap.user]
login_shell = "/bin/fish"
