[bootstrap.packages]
"brew:btop" = "latest"
"brew:fish" = "latest"
"brew:granted" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:keepassxc" = "latest"
"brew-cask:localsend" = "latest"
"brew-cask:font-monaspace" = "latest"
"brew-cask:syncthing-app" = "latest"
"brew-cask:firefox" = "latest"
"brew-cask:raycast" = "latest"
"brew-cask:tailscale-app" = "latest"
"brew-cask:space-rabbit" = "latest"
"brew-cask:tidal" = "latest"

[bootstrap.macos.dock]
autohide = true
show_recents = false
mru_spaces = false

[bootstrap.macos.keyboard]
press_and_hold = false

[bootstrap.macos.trackpad]
tap_to_click = true
