[tools]
aws = { version = "latest", symlink_bins = "true" }
btop = "latest"
bun = "latest"
claude = "latest"
deno = "latest"
direnv = "latest"
fzf = "latest"
go = "1.26"
golangci-lint = "latest"
granted = "latest"
herdr = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "0.12.4"
node = "26"
nub = "latest"
opencode = "latest"
pnpm = "11"
terraform = "latest"
uv = "latest"
bottom = "latest"
fastfetch = "latest"
usage = "latest"
jq = "latest"
gh = "latest"
tree-sitter = "latest"
ninja = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "go", "npm"]
