[bootstrap.packages]
"brew:btop" = "latest"
"brew:granted" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:keepassxc" = "latest"
"brew-cask:localsend" = "latest"
"brew-cask:font-monaspace" = "latest"
"brew-cask:battery" = "latest"
